# Disable the Gradle daemon for Continuous Integration servers as correctness
# is usually a priority over speed in CI environments. Using a fresh
# runtime for each build is more reliable since the runtime is completely
# isolated from any previous builds.
variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"

# Define the stages of the pipeline
stages:
  - build
  - test
  - sonarqube

# Build stage: compile the project and generate artifacts
build:
  stage: build
  script:
    - cd individual_project
    - ./gradlew assemble
  artifacts:
    paths:
      - build/libs/*.jar

# Test stage: run tests on the project
test:
  stage: test
  script:
    - cd individual_project
    - ./gradlew test

#SonarQube stage
sonarqube:
  stage: sonarqube
  script:
    - cd individual_project
    - ./gradlew sonarqube
